In [12]:
import numpy as np
import control as ctrl

# Define the transfer function numerator and denominator coefficients
num = [1, 0, 1]
den = [1, 6, 11, 5]

# Convert transfer function to state-space
sys_tf = ctrl.TransferFunction(num, den)
sys_ss = ctrl.tf2ss(sys_tf)  # Convert the transfer function to state-space directly

# Print state-space representation from transfer function
print("State-space representation from transfer function:")
print(sys_ss)

# Example 5-1 Part 1
A1 = np.array([[0, 1, 0],
               [0, 0, 1],
               [-5, -11, -6]])
B1 = np.array([[0], [0], [1]])
C1 = np.array([[1, 0, 1]])
D1 = np.array([[0]])
sys1 = ctrl.ss(A1, B1, C1, D1)
sys1_tf = ctrl.tf(sys1)

print("\nTransfer function sys1:\n", sys1_tf)

# Example 5-1 Part 2
A2 = np.array([[0, 0, -5],
               [1, 0, -11],
               [0, 1, -6]])
B2 = np.array([[1], [0], [1]])
C2 = np.array([[0, 0, 1]])
D2 = np.array([[0]])
sys2 = ctrl.ss(A2, B2, C2, D2)
sys2_tf = ctrl.tf(sys2)

print("\nTransfer function sys2:\n", sys2_tf)

# Example 5-1 Part 3
A3 = np.array([[0, 1, 0],
               [0, 0, 1],
               [-5, -11, -6]])
B3 = np.array([[1], [-6], [26]])
C3 = np.array([[1, 0, 0]])
D3 = np.array([[0]])
sys3 = ctrl.ss(A3, B3, C3, D3)
sys3_tf = ctrl.tf(sys3)

print("\nTransfer function sys3:\n", sys3_tf)

# Compute observability matrix for sys3 and print
O_sys3 = ctrl.obsv(sys3.A, sys3.C)
print("\nObservability matrix O_sys3:\n", O_sys3)

# Example 5-1 Part 4
A4 = np.array([[0, 0, -5],
               [1, 0, -11],
               [0, 1, -6]])
B4 = np.array([[1], [0], [0]])
C4 = np.array([[1, -6, 26]])
D4 = np.array([[0]])
sys4 = ctrl.ss(A4, B4, C4, D4)
sys4_tf = ctrl.tf(sys4)

print("\nTransfer function sys4:\n", sys4_tf)

# Compute controllability matrix for sys4 and print
C_sys4 = ctrl.ctrb(sys4.A, sys4.B)
print("\nControllability matrix C_sys4:\n", C_sys4)


State-space representation from transfer function:
<StateSpace>: sys[84]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']
States (3): ['x[0]', 'x[1]', 'x[2]']

A = [[ -6. -11.  -5.]
     [  1.   0.   0.]
     [  0.   1.   0.]]

B = [[1.]
     [0.]
     [0.]]

C = [[1. 0. 1.]]

D = [[0.]]


Transfer function sys1:
 <TransferFunction>: sys[87]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']


s^2 + 2.132e-14 s + 1
----------------------
s^3 + 6 s^2 + 11 s + 5


Transfer function sys2:
 <TransferFunction>: sys[89]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']


s^2 + 8.882e-15 s + 1
----------------------
s^3 + 6 s^2 + 11 s + 5


Transfer function sys3:
 <TransferFunction>: sys[91]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']


s^2 - 7.105e-15 s + 1
----------------------
s^3 + 6 s^2 + 11 s + 5


Observability matrix O_sys3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Transfer function sys4:
 <TransferFunction>: sys[93]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']


s^2 - 7.105e-15 s + 1
----------------------
