In [4]:
import numpy as np
from scipy.signal import StateSpace

# Define the state-space matrices
A = np.array([[0, 1, 0],
              [0, 0, 4.438],
              [0, -12, -24]])

b1 = np.array([[0],
               [0],
               [20]])

b2 = np.array([[0],
               [-7.396],
               [0]])

# Concatenate b1 and b2 along axis=1 to form B
B = np.hstack((b1, b2))

C = np.array([[1, 0, 0],
              [0, 1, 0]])

# D should be 2x2 to match the number of outputs (rows of C) and inputs (columns of B)
D = np.array([[0, 0],
              [0, 0]])

# Create the StateSpace object
DC_motor = StateSpace(A, B, C, D)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
eigenvalues_conjugate, eigenvectors_conjugate = np.linalg.eig(A.T)

print("Eigenvalues of A:")
print(eigenvalues)

print("\nEigenvectors of A:")
print(eigenvectors)

print("\nEigenvalues of A transpose:")
print(eigenvalues_conjugate)

print("\nEigenvectors of A transpose:")
print(eigenvectors_conjugate)


Eigenvalues of A:
[  0.          -2.47403548 -21.52596452]

Eigenvectors of A:
[[ 1.         -0.33290784  0.00938002]
 [ 0.          0.82362581 -0.20191394]
 [ 0.         -0.45914364  0.97935835]]

Eigenvalues of A transpose:
[-21.52596452  -2.47403548   0.        ]

Eigenvectors of A transpose:
[[ 0.          0.          0.90907852]
 [-0.48691774 -0.97940144  0.40967937]
 [-0.87344783 -0.20192283  0.07575654]]
