In [2]:
import numpy as np

# Define matrix A
A = np.array([
    [0, 1, 0, 0],
    [0, 0, -9.8, 0],
    [0, 0, 0, 1],
    [0, 0, 19.6, 0]
])

# Define vector B
B = np.array([0, 1, 0, 1]).reshape(-1, 1)

# Define matrix C
C = np.array([
    [1, 0, 0, 0],
    [0, 0, 1, 0]
])

# Compute Jordan form and transformation matrices
T, J = np.linalg.eig(A)

# Calculate transformed B and C matrices
T_inv = np.linalg.inv(J)
Bn = T_inv @ B
Cn = C @ J

print("Jordan form J:\n", J)
print("Transformation matrix T:\n", T)
print("Transformed B matrix Bn:\n", Bn)
print("Transformed C matrix Cn:\n", Cn)

# Example 3-13
A_example = np.array([
    [0, 1, 0, 3],
    [0, -1, 1, 10],
    [0, 0, 0, 1],
    [0, 0, -1, -2]
])

# Compute Jordan form and transformation matrices for Example 3-13
T_example, J_example = np.linalg.eig(A_example)

print("\nExample 3-13 Jordan form J:\n", J_example)
print("Example 3-13 transformation matrix T:\n", T_example)


Jordan form J:
 [[ 1.00000000e+000 -1.00000000e+000 -9.85329278e-002  9.85329278e-002]
 [ 0.00000000e+000  4.00833672e-292 -4.36223867e-001 -4.36223867e-001]
 [ 0.00000000e+000  0.00000000e+000  1.97065856e-001 -1.97065856e-001]
 [ 0.00000000e+000  0.00000000e+000  8.72447734e-001  8.72447734e-001]]
Transformation matrix T:
 [ 0.          0.          4.42718872 -4.42718872]
Transformed B matrix Bn:
 [[3.74220058e+291]
 [3.74220058e+291]
 [5.73100233e-001]
 [5.73100233e-001]]
Transformed C matrix Cn:
 [[ 1.         -1.         -0.09853293  0.09853293]
 [ 0.          0.          0.19706586 -0.19706586]]

Example 3-13 Jordan form J:
 [[ 1.00000000e+00+0.00000000e+00j -7.07106781e-01+0.00000000e+00j
   7.07106781e-01+0.00000000e+00j  7.07106781e-01-0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j  7.07106781e-01+0.00000000e+00j
  -7.07106781e-01+6.30641905e-09j -7.07106781e-01-6.30641905e-09j]
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   7.81174669e-19+5.25534921e